#!/bin/sh

if ! [ -x /usr/bin/blackholesocker ]; then
	exit 0
fi

case "$1" in
	start)
		start-stop-daemon -S -b -x /usr/bin/blackholesocker
		/usr/bin/StartMECam start
		;;
	stop)
		start-stop-daemon -K -x /usr/bin/blackholesocker
		;;
	restart|reload)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
